# These are supported funding model platforms

github: [gwdburst]
patreon: gwdburst
open_collective: gwdburst
ko_fi: gwdburst
tidelift: Debian/shell
community_bridge: de_GWD
liberapay: gwdburst
issuehunt: gwdburst
otechie: gwdburst
custom: ['https://www.paypal.me/jacyl4']
