# These are supported funding model platforms

github: [jacyl4]
patreon: jacyl4
open_collective: jacyl4
ko_fi: jacyl4
tidelift: Debian/shell
community_bridge: jacyl4
liberapay: jacyl4
issuehunt: jacyl4
otechie: jacyl4
custom: ['https://www.paypal.me/jacyl4']
